<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehicleModelsTableSeeder extends Seeder
{
  /**
  * Run the database seeds.
  *
  * @return void
  */
  public function run()
  {
    
    DB::table('vehicle_models')->delete();
    $models1 = array(
      array('id' =>1, 'make_id' =>1, 'code' => 'CL_MODELS', 'name' => 'CL Models (4)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>2, 'make_id' =>1, 'code' =>'2.2CL', 'name' => ' - 2.2CL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>3, 'make_id' =>1, 'code' =>'2.3CL', 'name' =>' - 2.3CL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>4, 'make_id' =>1, 'code' =>'3.0CL', 'name' =>' - 3.0CL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>5, 'make_id' =>1, 'code' =>'3.2CL', 'name' =>' - 3.2CL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>6, 'make_id' =>1, 'code' =>'ILX', 'name' =>'ILX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>7, 'make_id' =>1, 'code' =>'INTEG', 'name' =>'Integra','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>8, 'make_id' =>1, 'code' =>'LEGEND', 'name' =>'Legend','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>9, 'make_id' =>1, 'code' =>'MDX', 'name' =>'MDX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>10, 'make_id' =>1, 'code' =>'NSX', 'name' =>'NSX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>11, 'make_id' =>1, 'code' =>'RDX', 'name' =>'RDX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>12, 'make_id' =>1, 'code' =>'RL_MODELS', 'name' =>'RL Models (2)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>13, 'make_id' =>1, 'code' =>'3.5RL', 'name' =>' - 3.5 RL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>14, 'make_id' =>1, 'code' =>'RL', 'name' =>' - RL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>15, 'make_id' =>1, 'code' =>'RSX', 'name' =>'RSX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>16, 'make_id' =>1, 'code' =>'SLX', 'name' =>'SLX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>17, 'make_id' =>1, 'code' =>'TL_MODELS', 'name' =>'TL Models (3)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>18, 'make_id' =>1, 'code' =>'2.5TL', 'name' =>' - 2.5TL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>19, 'make_id' =>1, 'code' =>'3.2TL', 'name' =>' - 3.2TL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>20, 'make_id' =>1, 'code' =>'TL', 'name' =>' - TL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>21, 'make_id' =>1, 'code' =>'TSX', 'name' =>'TSX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>22, 'make_id' =>1, 'code' =>'VIGOR', 'name' =>'Vigor','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>23, 'make_id' =>1, 'code' =>'ZDX', 'name' =>'ZDX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>24, 'make_id' =>1, 'code' =>'ACUOTH', 'name' =>'Other Acura Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>25, 'make_id' =>2, 'code' =>'ALFA164', 'name' =>'164','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>26, 'make_id' =>2, 'code' =>'ALFA8C', 'name' =>'8C Competizione','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>27, 'make_id' =>2, 'code' =>'ALFAGT', 'name' =>'GTV-6','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>28, 'make_id' =>2, 'code' =>'MIL', 'name' =>'Milano','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>29, 'make_id' =>2, 'code' =>'SPID', 'name' =>'Spider','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>30, 'make_id' =>2, 'code' =>'ALFAOTH', 'name' =>'Other Alfa Romeo Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>31, 'make_id' =>3, 'code' =>'AMCALLIAN', 'name' =>'Alliance','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>32, 'make_id' =>3, 'code' =>'CON', 'name' =>'Concord','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>33, 'make_id' =>3, 'code' =>'EAGLE', 'name' =>'Eagle','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>34, 'make_id' =>3, 'code' =>'AMCENC', 'name' =>'Encore','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>35, 'make_id' =>3, 'code' =>'AMCSPIRIT', 'name' =>'Spirit','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>36, 'make_id' =>3, 'code' =>'AMCOTH', 'name' =>'Other AMC Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>37, 'make_id' =>4, 'code' =>'DB7', 'name' =>'DB7','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>38, 'make_id' =>4, 'code' =>'DB9', 'name' =>'DB9','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>39, 'make_id' =>4, 'code' =>'DBS', 'name' =>'DBS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>40, 'make_id' =>4, 'code' =>'LAGONDA', 'name' =>'Lagonda','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>41, 'make_id' =>4, 'code' =>'RAPIDE', 'name' =>'Rapide','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>42, 'make_id' =>4, 'code' =>'V12VANT', 'name' =>'V12 Vantage','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>43, 'make_id' =>4, 'code' =>'VANTAGE', 'name' =>'V8 Vantage','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>44, 'make_id' =>4, 'code' =>'VANQUISH', 'name' =>'Vanquish','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>45, 'make_id' =>4, 'code' =>'VIRAGE', 'name' =>'Virage','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>46, 'make_id' =>4, 'code' =>'UNAVAILAST', 'name' =>'Other Aston Martin Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>47, 'make_id' =>5, 'code' =>'AUDI100', 'name' =>'100','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>48, 'make_id' =>5, 'code' =>'AUDI200', 'name' =>'200','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>49, 'make_id' =>5, 'code' =>'4000', 'name' =>'4000','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>50, 'make_id' =>5, 'code' =>'5000', 'name' =>'5000','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>51, 'make_id' =>5, 'code' =>'80', 'name' =>'80','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>52, 'make_id' =>5, 'code' =>'90', 'name' =>'90','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>53, 'make_id' =>5, 'code' =>'A3', 'name' =>'A3','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>54, 'make_id' =>5, 'code' =>'A4', 'name' =>'A4','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>55, 'make_id' =>5, 'code' =>'A5', 'name' =>'A5','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>56, 'make_id' =>5, 'code' =>'A6', 'name' =>'A6','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>57, 'make_id' =>5, 'code' =>'A7', 'name' =>'A7','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>58, 'make_id' =>5, 'code' =>'A8', 'name' =>'A8','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>59, 'make_id' =>5, 'code' =>'ALLRDQUA', 'name' =>'allroad','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>60, 'make_id' =>5, 'code' =>'AUDICABRI', 'name' =>'Cabriolet','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>61, 'make_id' =>5, 'code' =>'AUDICOUPE', 'name' =>'Coupe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>62, 'make_id' =>5, 'code' =>'Q3', 'name' =>'Q3','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>63, 'make_id' =>5, 'code' =>'Q5', 'name' =>'Q5','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>64, 'make_id' =>5, 'code' =>'Q7', 'name' =>'Q7','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>65, 'make_id' =>5, 'code' =>'QUATTR', 'name' =>'Quattro','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>66, 'make_id' =>5, 'code' =>'R8', 'name' =>'R8','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>67, 'make_id' =>5, 'code' =>'RS4', 'name' =>'RS 4','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>68, 'make_id' =>5, 'code' =>'RS5', 'name' =>'RS 5','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>69, 'make_id' =>5, 'code' =>'RS6', 'name' =>'RS 6','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>70, 'make_id' =>5, 'code' =>'S4', 'name' =>'S4','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>71, 'make_id' =>5, 'code' =>'S5', 'name' =>'S5','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>72, 'make_id' =>5, 'code' =>'S6', 'name' =>'S6','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>73, 'make_id' =>5, 'code' =>'S7', 'name' =>'S7','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>74, 'make_id' =>5, 'code' =>'S8', 'name' =>'S8','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>75, 'make_id' =>5, 'code' =>'TT', 'name' =>'TT','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>76, 'make_id' =>5, 'code' =>'TTRS', 'name' =>'TT RS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>77, 'make_id' =>5, 'code' =>'TTS', 'name' =>'TTS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>78, 'make_id' =>5, 'code' =>'V8', 'name' =>'V8 Quattro','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>79, 'make_id' =>5, 'code' =>'AUDOTH', 'name' =>'Other Audi Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>80, 'make_id' =>6, 'code' =>'CONVERT', 'name' =>'Convertible','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>81, 'make_id' =>6, 'code' =>'COUPEAVANT', 'name' =>'Coupe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>82, 'make_id' =>6, 'code' =>'SEDAN', 'name' =>'Sedan','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>83, 'make_id' =>6, 'code' =>'UNAVAILAVA', 'name' =>'Other Avanti Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>84, 'make_id' =>7, 'code' =>'ARNAGE', 'name' =>'Arnage','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>85, 'make_id' =>7, 'code' =>'AZURE', 'name' =>'Azure','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>86, 'make_id' =>7, 'code' =>'BROOKLANDS', 'name' =>'Brooklands','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>87, 'make_id' =>7, 'code' =>'BENCONT', 'name' =>'Continental','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>88, 'make_id' =>7, 'code' =>'CORNICHE', 'name' =>'Corniche','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>89, 'make_id' =>7, 'code' =>'BENEIGHT', 'name' =>'Eight','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>90, 'make_id' =>7, 'code' =>'BENMUL', 'name' =>'Mulsanne','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>91, 'make_id' =>7, 'code' =>'BENTURBO', 'name' =>'Turbo R','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>92, 'make_id' =>7, 'code' =>'UNAVAILBEN', 'name' =>'Other Bentley Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>93, 'make_id' =>8, 'code' =>'1_SERIES', 'name' =>'1 Series (3)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>94, 'make_id' =>8, 'code' =>'128I', 'name' =>' - 128i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>95, 'make_id' =>8, 'code' =>'135I', 'name' =>' - 135i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>96, 'make_id' =>8, 'code' =>'135IS','name' => ' - 135is','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>97, 'make_id' =>8, 'code' =>'3_SERIES', 'name' =>'3 Series (29)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>98, 'make_id' =>8, 'code' =>'318I', 'name' =>' - 318i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>99, 'make_id' =>8, 'code' =>'318IC', 'name' =>' - 318iC','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>100, 'make_id' =>8, 'code' =>'318IS', 'name' =>' - 318iS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>101, 'make_id' =>8, 'code' =>'318TI', 'name' =>' - 318ti','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>102, 'make_id' =>8, 'code' =>'320I', 'name' =>' - 320i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>103, 'make_id' =>8, 'code' =>'323CI', 'name' =>' - 323ci','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>104, 'make_id' =>8, 'code' =>'323I', 'name' =>' - 323i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>105, 'make_id' =>8, 'code' =>'323IS', 'name' =>' - 323is','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>106, 'make_id' =>8, 'code' =>'323IT', 'name' =>' - 323iT','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>107, 'make_id' =>8, 'code' =>'325CI', 'name' =>' - 325Ci','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>108, 'make_id' =>8, 'code' =>'325E', 'name' =>' - 325e','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>109, 'make_id' =>8, 'code' =>'325ES', 'name' =>' - 325es','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>110, 'make_id' =>8, 'code' =>'325I', 'name' =>' - 325i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>111, 'make_id' =>8, 'code' =>'325IS', 'name' =>' - 325is','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>112, 'make_id' =>8, 'code' =>'325IX', 'name' =>' - 325iX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>113, 'make_id' =>8, 'code' =>'325XI', 'name' =>' - 325xi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>114, 'make_id' =>8, 'code' =>'328CI', 'name' =>' - 328Ci','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>115, 'make_id' =>8, 'code' =>'328I', 'name' =>' - 328i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>116, 'make_id' =>8, 'code' =>'328IS', 'name' =>' - 328iS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>117, 'make_id' =>8, 'code' =>'328XI', 'name' =>' - 328xi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>118, 'make_id' =>8, 'code' =>'330CI', 'name' =>' - 330Ci','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>119, 'make_id' =>8, 'code' =>'330I', 'name' =>' - 330i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>120, 'make_id' =>8, 'code' =>'330XI', 'name' =>' - 330xi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>121, 'make_id' =>8, 'code' =>'335D', 'name' =>' - 335d','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>122, 'make_id' =>8, 'code' =>'335I', 'name' =>' - 335i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>123, 'make_id' =>8, 'code' =>'335IS', 'name' =>' - 335is','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>124, 'make_id' =>8, 'code' =>'335XI', 'name' =>' - 335xi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>125, 'make_id' =>8, 'code' =>'ACTIVE3', 'name' =>' - ActiveHybrid 3','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>126, 'make_id' =>8, 'code' =>'BMW325', 'name' =>' - 325','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>127, 'make_id' =>8, 'code' =>'5_SERIES', 'name' =>'5 Series (19)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>128, 'make_id' =>8, 'code' =>'524TD', 'name' =>' - 524td','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>129, 'make_id' =>8, 'code' =>'525I', 'name' =>' - 525i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>130, 'make_id' =>8, 'code' =>'525XI', 'name' =>' - 525xi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>131, 'make_id' =>8, 'code' =>'528E', 'name' =>' - 528e','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>132, 'make_id' =>8, 'code' =>'528I', 'name' =>' - 528i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>133, 'make_id' =>8, 'code' =>'528IT', 'name' =>' - 528iT','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>134, 'make_id' =>8, 'code' =>'528XI', 'name' =>' - 528xi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>135, 'make_id' =>8, 'code' =>'530I', 'name' =>' - 530i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>136, 'make_id' =>8, 'code' =>'530IT', 'name' =>' - 530iT','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>137, 'make_id' =>8, 'code' =>'530XI', 'name' =>' - 530xi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>138, 'make_id' =>8, 'code' =>'533I', 'name' =>' - 533i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>139, 'make_id' =>8, 'code' =>'535I', 'name' =>' - 535i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>140, 'make_id' =>8, 'code' =>'535IGT', 'name' =>' - 535i Gran Turismo','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>141, 'make_id' =>8, 'code' =>'535XI', 'name' =>' - 535xi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>142, 'make_id' =>8, 'code' =>'540I', 'name' =>' - 540i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>143, 'make_id' =>8, 'code' =>'545I', 'name' =>' - 545i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>144, 'make_id' =>8, 'code' =>'550I', 'name' =>' - 550i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>145, 'make_id' =>8, 'code' =>'550IGT', 'name' =>' - 550i Gran Turismo','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>146, 'make_id' =>8, 'code' =>'ACTIVE5', 'name' =>' - ActiveHybrid 5','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>147, 'make_id' =>8, 'code' =>'6_SERIES', 'name' =>'6 Series (8)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>148, 'make_id' =>8, 'code' =>'633CSI', 'name' =>' - 633CSi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>149, 'make_id' =>8, 'code' =>'635CSI', 'name' =>' - 635CSi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>150, 'make_id' =>8, 'code' =>'640I', 'name' =>' - 640i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>151, 'make_id' =>8, 'code' =>'640IGC', 'name' =>' - 640i Gran Coupe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>152, 'make_id' =>8, 'code' =>'645CI', 'name' =>' - 645Ci','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>153, 'make_id' =>8, 'code' =>'650I', 'name' =>' - 650i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>154, 'make_id' =>8, 'code' =>'650IGC', 'name' =>' - 650i Gran Coupe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>155, 'make_id' =>8, 'code' =>'L6', 'name' =>' - L6','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>156, 'make_id' =>8, 'code' =>'7_SERIES', 'name' =>'7 Series (15)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>157, 'make_id' =>8, 'code' =>'733I', 'name' =>' - 733i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>158, 'make_id' =>8, 'code' =>'735I', 'name' =>' - 735i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>159, 'make_id' =>8, 'code' =>'735IL', 'name' =>' - 735iL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>160, 'make_id' =>8, 'code' =>'740I', 'name' =>' - 740i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>161, 'make_id' =>8, 'code' =>'740IL', 'name' =>' - 740iL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>162, 'make_id' =>8, 'code' =>'740LI', 'name' =>' - 740Li','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>163, 'make_id' =>8, 'code' =>'745I', 'name' =>' - 745i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>164, 'make_id' =>8, 'code' =>'745LI', 'name' =>' - 745Li','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>165, 'make_id' =>8, 'code' =>'750I', 'name' =>' - 750i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>166, 'make_id' =>8, 'code' =>'750IL', 'name' =>' - 750iL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>167, 'make_id' =>8, 'code' =>'750LI', 'name' =>' - 750Li','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>168, 'make_id' =>8, 'code' =>'760I', 'name' =>' - 760i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>169, 'make_id' =>8, 'code' =>'760LI', 'name' =>' - 760Li','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>170, 'make_id' =>8, 'code' =>'ACTIVE7', 'name' =>' - ActiveHybrid 7','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>171, 'make_id' =>8, 'code' =>'ALPINAB7', 'name' =>' - Alpina B7','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>172, 'make_id' =>8, 'code' =>'8_SERIES', 'name' =>'8 Series (4)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>173, 'make_id' =>8, 'code' =>'840CI', 'name' =>' - 840Ci','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>174, 'make_id' =>8, 'code' =>'850CI', 'name' =>' - 850Ci','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>175, 'make_id' =>8, 'code' =>'850CSI', 'name' =>' - 850CSi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>176, 'make_id' =>8, 'code' =>'850I', 'name' =>' - 850i','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>177, 'make_id' =>8, 'code' =>'L_SERIES', 'name' =>'L Series (1)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>178, 'make_id' =>8, 'code' =>'L7', 'name' =>' - L7','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>179, 'make_id' =>8, 'code' =>'M_SERIES', 'name' =>'M Series (8)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>180, 'make_id' =>8, 'code' =>'1SERIESM', 'name' =>' - 1 Series M','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>181, 'make_id' =>8, 'code' =>'BMWMCOUPE', 'name' =>' - M Coupe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>182, 'make_id' =>8, 'code' =>'BMWROAD', 'name' =>' - M Roadster','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>183, 'make_id' =>8, 'code' =>'M3', 'name' =>' - M3','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>184, 'make_id' =>8, 'code' =>'M5', 'name' =>' - M5','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>185, 'make_id' =>8, 'code' =>'M6', 'name' =>' - M6','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>186, 'make_id' =>8, 'code' =>'X5M', 'name' =>' - X5 M','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>187, 'make_id' =>8, 'code' =>'X6M', 'name' =>' - X6 M','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>188, 'make_id' =>8, 'code' =>'X_SERIES', 'name' =>'X Series (5)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>189, 'make_id' =>8, 'code' =>'ACTIVEX6', 'name' =>' - ActiveHybrid X6','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>190, 'make_id' =>8, 'code' =>'X1', 'name' =>' - X1','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>191, 'make_id' =>8, 'code' =>'X3', 'name' =>' - X3','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>192, 'make_id' =>8, 'code' =>'X5', 'name' =>' - X5','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>193, 'make_id' =>8, 'code' =>'X6', 'name' =>' - X6','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>194, 'make_id' =>8, 'code' =>'Z_SERIES', 'name' =>'Z Series (3)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>195, 'make_id' =>8, 'code' =>'Z3', 'name' =>' - Z3','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>196, 'make_id' =>8, 'code' =>'Z4', 'name' =>' - Z4','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>197, 'make_id' =>8, 'code' =>'Z8', 'name' =>' - Z8','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>198, 'make_id' =>8, 'code' =>'BMWOTH', 'name' =>'Other BMW Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>199, 'make_id' =>9, 'code' =>'CENT', 'name' =>'Century','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>200, 'make_id' =>9, 'code' =>'ELEC', 'name' =>'Electra','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>201, 'make_id' =>9, 'code' =>'ENCLAVE', 'name' =>'Enclave','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>202, 'make_id' =>9, 'code' =>'BUIENC', 'name' =>'Encore','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>203, 'make_id' =>9, 'code' =>'LACROSSE', 'name' =>'LaCrosse','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>204, 'make_id' =>9, 'code' =>'LESA', 'name' =>'Le Sabre','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>205, 'make_id' =>9, 'code' =>'LUCERNE', 'name' =>'Lucerne','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>206, 'make_id' =>9, 'code' =>'PARK', 'name' =>'Park Avenue','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>207, 'make_id' =>9, 'code' =>'RAINIER', 'name' =>'Rainier','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>208, 'make_id' =>9, 'code' =>'REATTA', 'name' =>'Reatta','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>209, 'make_id' =>9, 'code' =>'REG', 'name' =>'Regal','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>210, 'make_id' =>9, 'code' =>'RENDEZVOUS', 'name' =>'Rendezvous','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>211, 'make_id' =>9, 'code' =>'RIV', 'name' =>'Riviera','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>212, 'make_id' =>9, 'code' =>'BUICKROAD', 'name' =>'Roadmaster','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>213, 'make_id' =>9, 'code' =>'SKYH', 'name' =>'Skyhawk','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>214, 'make_id' =>9, 'code' =>'SKYL', 'name' =>'Skylark','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>215, 'make_id' =>9, 'code' =>'SOMER', 'name' =>'Somerset','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>216, 'make_id' =>9, 'code' =>'TERRAZA', 'name' =>'Terraza','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>217, 'make_id' =>9, 'code' =>'BUVERANO', 'name' =>'Verano','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>218, 'make_id' =>9, 'code' =>'BUOTH', 'name' =>'Other Buick Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>219, 'make_id' =>10,'code' => 'ALLANT', 'name' =>'Allante','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>220, 'make_id' =>10,'code' => 'ATS', 'name' =>'ATS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>221, 'make_id' =>10,'code' => 'BROUGH', 'name' =>'Brougham','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>222, 'make_id' =>10,'code' => 'CATERA', 'name' =>'Catera','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>223, 'make_id' =>10,'code' => 'CIMA', 'name' =>'Cimarron','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>224, 'make_id' =>10, 'code' =>'CTS', 'name' =>'CTS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>225, 'make_id' =>10, 'code' =>'DEV', 'name' =>'De Ville','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>226, 'make_id' =>10, 'code' =>'DTS', 'name' =>'DTS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>227, 'make_id' =>10, 'code' =>'ELDO', 'name' =>'Eldorado','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>228, 'make_id' =>10, 'code' =>'ESCALA', 'name' =>'Escalade','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>229, 'make_id' =>10, 'code' =>'ESCALAESV', 'name' =>'Escalade ESV','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>230, 'make_id' =>10, 'code' =>'EXT', 'name' =>'Escalade EXT','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>231, 'make_id' =>10, 'code' =>'FLEE', 'name' =>'Fleetwood','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>232, 'make_id' =>10, 'code' =>'SEV', 'name' =>'Seville','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>233, 'make_id' =>10, 'code' =>'SRX', 'name' =>'SRX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>234, 'make_id' =>10, 'code' =>'STS', 'name' =>'STS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>235, 'make_id' =>10, 'code' =>'XLR', 'name' =>'XLR','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>236, 'make_id' =>10, 'code' =>'XTS', 'name' =>'XTS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>237, 'make_id' =>10, 'code' =>'CADOTH', 'name' =>'Other Cadillac Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>238, 'make_id' =>11, 'code' =>'ASTRO', 'name' =>'Astro','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>239, 'make_id' =>11, 'code' =>'AVALNCH', 'name' =>'Avalanche','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>240, 'make_id' =>11, 'code' =>'AVEO', 'name' =>'Aveo','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>241, 'make_id' =>11, 'code' =>'AVEO5', 'name' =>'Aveo5','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>242, 'make_id' =>11, 'code' =>'BERETT', 'name' =>'Beretta','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>243, 'make_id' =>11, 'code' =>'BLAZER', 'name' =>'Blazer','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>244, 'make_id' =>11, 'code' =>'CAM', 'name' =>'Camaro','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>245, 'make_id' =>11, 'code' =>'CAP', 'name' =>'Caprice','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>246, 'make_id' =>11, 'code' =>'CHECAPS', 'name' =>'Captiva Sport','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>247, 'make_id' =>11, 'code' =>'CAV', 'name' =>'Cavalier','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>248, 'make_id' =>11, 'code' =>'CELE', 'name' =>'Celebrity','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>249, 'make_id' =>11, 'code' =>'CHEVETTE', 'name' =>'Chevette','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>250, 'make_id' =>11, 'code' =>'CITATION', 'name' =>'Citation','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>251, 'make_id' =>11, 'code' =>'COBALT', 'name' =>'Cobalt','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>252, 'make_id' =>11, 'code' =>'COLORADO', 'name' =>'Colorado','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>253, 'make_id' =>11, 'code' =>'CORSI', 'name' =>'Corsica','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>254, 'make_id' =>11, 'code' =>'CORV', 'name' =>'Corvette','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>255, 'make_id' =>11, 'code' =>'CRUZE', 'name' =>'Cruze','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>256, 'make_id' =>11, 'code' =>'ELCAM', 'name' =>'El Camino','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>257, 'make_id' =>11, 'code' =>'EQUINOX', 'name' =>'Equinox','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>258, 'make_id' =>11, 'code' =>'G15EXP', 'name' =>'Express Van','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>259, 'make_id' =>11, 'code' =>'G10', 'name' =>'G Van','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>260, 'make_id' =>11, 'code' =>'HHR', 'name' =>'HHR','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>261, 'make_id' =>11, 'code' =>'CHEVIMP', 'name' =>'Impala','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>262, 'make_id' =>11, 'code' =>'KODC4500', 'name' =>'Kodiak C4500','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>263, 'make_id' =>11, 'code' =>'LUMINA', 'name' =>'Lumina','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>264, 'make_id' =>11, 'code' =>'LAPV', 'name' =>'Lumina APV','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>265, 'make_id' =>11, 'code' =>'LUV', 'name' =>'LUV','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>266, 'make_id' =>11, 'code' =>'MALI', 'name' =>'Malibu','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>267, 'make_id' =>11, 'code' =>'CHVMETR', 'name' =>'Metro','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>268, 'make_id' =>11, 'code' =>'CHEVMONT', 'name' =>'Monte Carlo','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>269, 'make_id' =>11, 'code' =>'NOVA', 'name' =>'Nova','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>270, 'make_id' =>11, 'code' =>'CHEVPRIZM', 'name' =>'Prizm','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>271, 'make_id' =>11, 'code' =>'CHVST', 'name' =>'S10 Blazer','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>272, 'make_id' =>11, 'code' =>'S10PICKUP', 'name' =>'S10 Pickup','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>273, 'make_id' =>11, 'code' =>'CHEV150','name' => 'Silverado and other C/K1500','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>274, 'make_id' =>11, 'code' =>'CHEVC25', 'name' =>'Silverado and other C/K2500','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>275, 'make_id' =>11, 'code' =>'CH3500PU','name' => 'Silverado and other C/K3500','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>276, 'make_id' =>11, 'code' =>'SONIC', 'name' =>'Sonic','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>277, 'make_id' =>11, 'code' =>'SPARK', 'name' =>'Spark','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>278, 'make_id' =>11, 'code' =>'CHEVSPEC','name' =>'Spectrum','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>279, 'make_id' =>11, 'code' =>'CHSPRINT', 'name' =>'Sprint','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>280, 'make_id' =>11, 'code' =>'SSR', 'name' =>'SSR','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>281, 'make_id' =>11, 'code' =>'CHEVSUB', 'name' =>'Suburban','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>282, 'make_id' =>11, 'code' =>'TAHOE', 'name' =>'Tahoe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>283, 'make_id' =>11, 'code' =>'TRACKE', 'name' =>'Tracker','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>284, 'make_id' =>11, 'code' =>'TRAILBLZ','name' => 'TrailBlazer','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>285, 'make_id' =>11, 'code' =>'TRAILBZEXT','name' => 'TrailBlazer EXT','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>286, 'make_id' =>11, 'code' =>'TRAVERSE','name' => 'Traverse','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>287, 'make_id' =>11, 'code' =>'UPLANDER', 'name' =>'Uplander','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>288, 'make_id' =>11, 'code' =>'VENTUR','name' => 'Venture','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>289, 'make_id' =>11, 'code' =>'VOLT', 'name' =>'Volt','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>290, 'make_id' =>11, 'code' =>'CHEOTH','name' => 'Other Chevrolet Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>291, 'make_id' =>12, 'code' =>'CHRYS200','name' => '200','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>292, 'make_id' =>12, 'code' =>'300', 'name' =>'300','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>293, 'make_id' =>12, 'code' =>'CHRY300','name' => '300M','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>294, 'make_id' =>12, 'code' =>'ASPEN', 'name' =>'Aspen','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>295, 'make_id' =>12, 'code' =>'CARAVAN','name' => 'Caravan','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>296, 'make_id' =>12, 'code' =>'CIRRUS','name' => 'Cirrus','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>297, 'make_id' =>12, 'code' =>'CONC', 'name' =>'Concorde','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>298, 'make_id' =>12, 'code' =>'CHRYCONQ', 'name' =>'Conquest','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>299, 'make_id' =>12, 'code' =>'CORDOBA', 'name' =>'Cordoba','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>300, 'make_id' =>12, 'code' =>'CROSSFIRE', 'name' =>'Crossfire','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>301, 'make_id' =>12, 'code' =>'ECLASS', 'name' =>'E Class','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>302, 'make_id' =>12, 'code' =>'FIFTH', 'name' =>'Fifth Avenue','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>303, 'make_id' =>12, 'code' =>'CHRYGRANDV','name' => 'Grand Voyager','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>304, 'make_id' =>12, 'code' =>'IMPE', 'name' =>'Imperial','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>305, 'make_id' =>12, 'code' =>'INTREPID','name' => 'Intrepid','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>306, 'make_id' =>12, 'code' =>'CHRYLAS','name' => 'Laser','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>307, 'make_id' =>12, 'code' =>'LEBA', 'name' =>'LeBaron','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>308, 'make_id' =>12, 'code' =>'LHS', 'name' =>'LHS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>309, 'make_id' =>12, 'code' =>'CHRYNEON','name' => 'Neon','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>310, 'make_id' =>12, 'code' =>'NY', 'name' =>'New Yorker','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>311, 'make_id' =>12, 'code' =>'NEWPORT', 'name' =>'Newport','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>312, 'make_id' =>12, 'code' =>'PACIFICA','name' => 'Pacifica','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>313, 'make_id' =>12, 'code' =>'CHPROWLE','name' => 'Prowler','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>314, 'make_id' =>12, 'code' =>'PTCRUIS', 'name' =>'PT Cruiser','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>315, 'make_id' =>12, 'code' =>'CHRYSEB','name' => 'Sebring','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>316, 'make_id' =>12, 'code' =>'CHRYTC', 'name' =>'TC by Maserati','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>317, 'make_id' =>12, 'code' =>'TANDC', 'name' =>'Town & Country','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>318, 'make_id' =>12, 'code' =>'VOYAGER', 'name' =>'Voyager','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>319, 'make_id' =>12, 'code' =>'CHOTH','name' => 'Other Chrysler Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>320, 'make_id' =>13, 'code' =>'LANOS', 'name' =>'Lanos','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>321, 'make_id' =>13, 'code' =>'LEGANZA', 'name' =>'Leganza','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>322, 'make_id' =>13, 'code' =>'NUBIRA', 'name' =>'Nubira','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>323, 'make_id' =>13, 'code' =>'DAEOTH', 'name' =>'Other Daewoo Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>324, 'make_id' =>14, 'code' =>'CHAR', 'name' =>'Charade','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>325, 'make_id' =>14, 'code' =>'ROCKY','name' => 'Rocky','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>326, 'make_id' =>14, 'code' =>'DAIHOTH','name' => 'Other Daihatsu Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>327, 'make_id' =>15, 'code' =>'DAT200SX','name' => '200SX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>328, 'make_id' =>15, 'code' =>'DAT210','name' => '210','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>329, 'make_id' =>15, 'code' =>'280Z','name' => '280ZX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>330, 'make_id' =>15, 'code' =>'300ZX', 'name' =>'300ZX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>331, 'make_id' =>15, 'code' =>'310','name' => '310','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>332, 'make_id' =>15, 'code' =>'510', 'name' =>'510','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>333, 'make_id' =>15, 'code' =>'720', 'name' =>'720','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>334, 'make_id' =>15, 'code' =>'810', 'name' =>'810','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>335, 'make_id' =>15, 'code' =>'DATMAX','name' => 'Maxima','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>336, 'make_id' =>15, 'code' =>'DATPU', 'name' =>'Pickup','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>337, 'make_id' =>15, 'code' =>'PUL', 'name' =>'Pulsar','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>338, 'make_id' =>15, 'code' =>'DATSENT', 'name' =>'Sentra','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>339, 'make_id' =>15, 'code' =>'STAN', 'name' =>'Stanza','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>340, 'make_id' =>15, 'code' =>'DATOTH', 'name' =>'Other Datsun Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>341, 'make_id' =>16, 'code' =>'DMC12', 'name' =>'DMC-12','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>342, 'make_id' =>17, 'code' =>'400', 'name' =>'400','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>343, 'make_id' =>17, 'code' =>'DOD600','name' => '600','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>344, 'make_id' =>17, 'code' =>'ARI', 'name' =>'Aries','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>345, 'make_id' =>17, 'code' =>'AVENGR','name' => 'Avenger','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>346, 'make_id' =>17, 'code' =>'CALIBER','name' => 'Caliber','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>347, 'make_id' =>17, 'code' =>'DODCARA','name' => 'Caravan','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>348, 'make_id' =>17, 'code' =>'CHALLENGER','name' => 'Challenger','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>349, 'make_id' =>17, 'code' =>'DODCHAR', 'name' =>'Charger','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>350, 'make_id' =>17, 'code' =>'DODCOLT', 'name' =>'Colt','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>351, 'make_id' =>17, 'code' =>'DODCONQ', 'name' =>'Conquest','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>352, 'make_id' =>17, 'code' =>'DODDW', 'name' =>'D/W Truck','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>353, 'make_id' =>17, 'code' =>'DAKOTA', 'name' =>'Dakota','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>354, 'make_id' =>17, 'code' =>'DODDART', 'name' =>'Dart','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>355, 'make_id' =>17, 'code' =>'DAY', 'name' =>'Daytona','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>356, 'make_id' =>17, 'code' =>'DIPLOMA', 'name' =>'Diplomat','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>357, 'make_id' =>17, 'code' =>'DURANG','name' => 'Durango','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>358, 'make_id' =>17, 'code' =>'DODDYNA', 'name' =>'Dynasty','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>359, 'make_id' =>17, 'code' =>'GRANDCARAV','name' => 'Grand Caravan','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>360, 'make_id' =>17, 'code' =>'INTRE','name' => 'Intrepid','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>361, 'make_id' =>17, 'code' =>'JOURNEY','name' => 'Journey','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>362, 'make_id' =>17, 'code' =>'LANCERDODG','name' => 'Lancer','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>363, 'make_id' =>17, 'code' =>'MAGNUM','name' => 'Magnum','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>364, 'make_id' =>17, 'code' =>'MIRADA', 'name' =>'Mirada','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>365, 'make_id' =>17, 'code' =>'MONACO', 'name' =>'Monaco','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>366, 'make_id' =>17, 'code' =>'DODNEON','name' => 'Neon','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>367, 'make_id' =>17, 'code' =>'NITRO','name' => 'Nitro','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>368, 'make_id' =>17, 'code' =>'OMNI', 'name' =>'Omni','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>369, 'make_id' =>17, 'code' =>'RAIDER', 'name' =>'Raider','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>370, 'make_id' =>17, 'code' =>'RAM1504WD','name' => 'Ram 1500 Truck','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>371, 'make_id' =>17, 'code' =>'RAM25002WD','name' => 'Ram 2500 Truck','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>372, 'make_id' =>17, 'code' =>'RAM3502WD', 'name' =>'Ram 3500 Truck','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>373, 'make_id' =>17, 'code' =>'RAM4500','name' => 'Ram 4500 Truck','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>374, 'make_id' =>17, 'code' =>'DODD50', 'name' =>'Ram 50 Truck','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>375, 'make_id' =>17, 'code' =>'CV','name' => 'RAM C/V','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>376, 'make_id' =>17, 'code' =>'RAMSRT10','name' => 'Ram SRT-10','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>377, 'make_id' =>17, 'code' =>'RAMVANV8','name' => 'Ram Van','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>378, 'make_id' =>17, 'code' =>'RAMWAGON', 'name' =>'Ram Wagon','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>379, 'make_id' =>17, 'code' =>'RAMCGR', 'name' =>'Ramcharger','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>380, 'make_id' =>17, 'code' =>'RAMPAGE','name' => 'Rampage','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>381, 'make_id' =>17, 'code' =>'DODSHAD','name' => 'Shadow','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>382, 'make_id' =>17, 'code' =>'DODSPIR','name' => 'Spirit','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>383, 'make_id' =>17, 'code' =>'SPRINTER','name' => 'Sprinter','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>384, 'make_id' =>17, 'code' =>'SRT4','name' => 'SRT-4','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>385, 'make_id' =>17, 'code' =>'STREGIS', 'name' =>'St. Regis','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>386, 'make_id' =>17, 'code' =>'STEAL','name' => 'Stealth','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>387, 'make_id' =>17, 'code' =>'STRATU','name' => 'Stratus','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>388, 'make_id' =>17, 'code' =>'VIPER','name' => 'Viper','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>389, 'make_id' =>17, 'code' =>'DOOTH', 'name' =>'Other Dodge Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>390, 'make_id' =>18, 'code' =>'EAGLEMED', 'name' =>'Medallion','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>391, 'make_id' =>18, 'code' =>'EAGLEPREM', 'name' =>'Premier','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>392, 'make_id' =>18, 'code' =>'SUMMIT','name' => 'Summit','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>393, 'make_id' =>18, 'code' =>'TALON', 'name' =>'Talon','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>394, 'make_id' =>18, 'code' =>'VISION','name' => 'Vision','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>395, 'make_id' =>18, 'code' =>'EAGOTH', 'name' =>'Other Eagle Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>396, 'make_id' =>19, 'code' =>'308GTB', 'name' =>'308 GTB Quattrovalvole','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>397, 'make_id' =>19, 'code' =>'308TBI', 'name' =>'308 GTBI','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>398, 'make_id' =>19, 'code' =>'308GTS', 'name' =>'308 GTS Quattrovalvole','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>399, 'make_id' =>19, 'code' =>'308TSI','name' => '308 GTSI','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>400, 'make_id' =>19, 'code' =>'328GTB', 'name' =>'328 GTB','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>401, 'make_id' =>19, 'code' =>'328GTS', 'name' =>'328 GTS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>402, 'make_id' =>19, 'code' =>'348GTB', 'name' =>'348 GTB','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>403, 'make_id' =>19, 'code' =>'348GTS', 'name' =>'348 GTS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>404, 'make_id' =>19, 'code' =>'348SPI', 'name' =>'348 Spider','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>405, 'make_id' =>19, 'code' =>'348TB','name' => '348 TB','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>406, 'make_id' =>19, 'code' =>'348TS', 'name' =>'348 TS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>407, 'make_id' =>19, 'code' =>'360','name' => '360','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>408, 'make_id' =>19, 'code' =>'456GT','name' => '456 GT','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>409, 'make_id' =>19, 'code' =>'456MGT', 'name' =>'456M GT','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>410, 'make_id' =>19, 'code' =>'458ITALIA','name' => '458 Italia','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>411, 'make_id' =>19, 'code' =>'512BBI', 'name' =>'512 BBi','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>412, 'make_id' =>19, 'code' =>'512M', 'name' =>'512M','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>413, 'make_id' =>19, 'code' =>'512TR','name' => '512TR','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>414, 'make_id' =>19, 'code' =>'550M', 'name' =>'550 Maranello','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>415, 'make_id' =>19, 'code' =>'575M','name' => '575M Maranello','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>416, 'make_id' =>19, 'code' =>'599GTB', 'name' =>'599 GTB Fiorano','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>417, 'make_id' =>19, 'code' =>'599GTO','name' => '599 GTO','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>418, 'make_id' =>19, 'code' =>'612SCAGLIE','name' => '612 Scaglietti','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>419, 'make_id' =>19, 'code' =>'FERCALIF', 'name' =>'California','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>420, 'make_id' =>19, 'code' =>'ENZO', 'name' =>'Enzo','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>421, 'make_id' =>19, 'code' =>'F355','name' => 'F355','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>422, 'make_id' =>19, 'code' =>'F40', 'name' =>'F40','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>423, 'make_id' =>19, 'code' =>'F430','name' => 'F430','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>424, 'make_id' =>19, 'code' =>'F50', 'name' =>'F50','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>425, 'make_id' =>19, 'code' =>'FERFF','name' => 'FF','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>426, 'make_id' =>19, 'code' =>'MOND','name' => 'Mondial','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>427, 'make_id' =>19, 'code' =>'TEST', 'name' =>'Testarossa','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>428, 'make_id' =>19, 'code' =>'UNAVAILFER','name' => 'Other Ferrari Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>429, 'make_id' =>20, 'code' =>'2000', 'name' =>'2000 Spider','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>430, 'make_id' =>20, 'code' =>'FIAT500','name' => '500','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>431, 'make_id' =>20, 'code' =>'BERTON', 'name' =>'Bertone X1/9','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>432, 'make_id' =>20, 'code' =>'BRAVA', 'name' =>'Brava','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>433, 'make_id' =>20, 'code' =>'PININ', 'name' =>'Pininfarina Spider','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>434, 'make_id' =>20, 'code' =>'STRADA', 'name' =>'Strada','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>435, 'make_id' =>20, 'code' =>'FIATX19','name' => 'X1/9','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>436, 'make_id' =>20, 'code' =>'UNAVAILFIA', 'name' =>'Other Fiat Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>437, 'make_id' =>21, 'code' =>'KARMA', 'name' =>'Karma','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>438, 'make_id' =>22, 'code' =>'AERO', 'name' =>'Aerostar','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>439, 'make_id' =>22, 'code' =>'ASPIRE','name' => 'Aspire','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>440, 'make_id' =>22, 'code' =>'BRON','name' => 'Bronco','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>441, 'make_id' =>22, 'code' =>'B2', 'name' =>'Bronco II','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>442, 'make_id' =>22, 'code' =>'FOCMAX','name' => 'C-MAX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>443, 'make_id' =>22, 'code' =>'FORDCLUB', 'name' =>'Club Wagon','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>444, 'make_id' =>22, 'code' =>'CONTOUR', 'name' =>'Contour','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>445, 'make_id' =>22, 'code' =>'COURIER','name' => 'Courier','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>446, 'make_id' =>22, 'code' =>'CROWNVIC', 'name' =>'Crown Victoria','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>447, 'make_id' =>22, 'code' =>'E150ECON','name' => 'E-150 and Econoline 150','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>448, 'make_id' =>22, 'code' =>'E250ECON','name' => 'E-250 and Econoline 250','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>449, 'make_id' =>22, 'code' =>'E350ECON','name' => 'E-350 and Econoline 350','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>450, 'make_id' =>22, 'code' =>'EDGE', 'name' =>'Edge','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>451, 'make_id' =>22, 'code' =>'ESCAPE', 'name' =>'Escape','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>452, 'make_id' =>22, 'code' =>'ESCO', 'name' =>'Escort','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>453, 'make_id' =>22, 'code' =>'EXCURSION', 'name' =>'Excursion','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>454, 'make_id' =>22, 'code' =>'EXP', 'name' =>'EXP','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>455, 'make_id' =>22, 'code' =>'EXPEDI','name' => 'Expedition','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>456, 'make_id' =>22, 'code' =>'EXPEDIEL','name' => 'Expedition EL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>457, 'make_id' =>22, 'code' =>'EXPLOR', 'name' =>'Explorer','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>458, 'make_id' =>22, 'code' =>'SPORTTRAC','name' => 'Explorer Sport Trac','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>459, 'make_id' =>22, 'code' =>'F100', 'name' =>'F100','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>460, 'make_id' =>22, 'code' =>'F150PICKUP', 'name' =>'F150','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>461, 'make_id' =>22, 'code' =>'F250', 'name' =>'F250','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>462, 'make_id' =>22, 'code' =>'F350', 'name' =>'F350','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>463, 'make_id' =>22, 'code' =>'F450', 'name' =>'F450','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>464, 'make_id' =>22, 'code' =>'FAIRM', 'name' =>'Fairmont','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>465, 'make_id' =>22, 'code' =>'FESTIV','name' => 'Festiva','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>466, 'make_id' =>22, 'code' =>'FIESTA', 'name' =>'Fiesta','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>467, 'make_id' =>22, 'code' =>'FIVEHUNDRE','name' => 'Five Hundred','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>468, 'make_id' =>22, 'code' =>'FLEX','name' => 'Flex','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>469, 'make_id' =>22, 'code' =>'FOCUS', 'name' =>'Focus','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>470, 'make_id' =>22, 'code' =>'FREESTAR', 'name' =>'Freestar','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>471, 'make_id' =>22, 'code' =>'FREESTYLE','name' => 'Freestyle','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>472, 'make_id' =>22, 'code' =>'FUSION','name' => 'Fusion','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>473, 'make_id' =>22, 'code' =>'GRANADA', 'name' =>'Granada','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>474, 'make_id' =>22, 'code' =>'GT','name' => 'GT','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>475, 'make_id' =>22, 'code' =>'LTD','name' => 'LTD','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>476, 'make_id' =>22, 'code' =>'MUST','name' => 'Mustang','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>477, 'make_id' =>22, 'code' =>'PROBE', 'name' =>'Probe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>478, 'make_id' =>22, 'code' =>'RANGER', 'name' =>'Ranger','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>479, 'make_id' =>22, 'code' =>'TAURUS', 'name' =>'Taurus','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>480, 'make_id' =>22, 'code' =>'TAURUSX','name' => 'Taurus X','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>481, 'make_id' =>22, 'code' =>'TEMPO','name' => 'Tempo','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>482, 'make_id' =>22, 'code' =>'TBIRD','name' => 'Thunderbird','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>483, 'make_id' =>22, 'code' =>'TRANSCONN', 'name' =>'Transit Connect','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>484, 'make_id' =>22, 'code' =>'WINDST', 'name' =>'Windstar','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>485, 'make_id' =>22, 'code' =>'FORDZX2', 'name' =>'ZX2 Escort','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>486, 'make_id' =>22, 'code' =>'FOOTH','name' => 'Other Ford Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>487, 'make_id' =>23, 'code' =>'FRESPRINT','name' => 'Sprinter','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>488, 'make_id' =>24, 'code' =>'GEOMETRO', 'name' =>'Metro','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>489, 'make_id' =>24, 'code' =>'GEOPRIZM','name' => 'Prizm','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>490, 'make_id' =>24, 'code' =>'SPECT','name' => 'Spectrum','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>491, 'make_id' =>24, 'code' =>'STORM', 'name' =>'Storm','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>492, 'make_id' =>24, 'code' =>'GEOTRACK','name' => 'Tracker','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>493, 'make_id' =>24, 'code' =>'GEOOTH', 'name' =>'Other Geo Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>494, 'make_id' =>25, 'code' =>'ACADIA','name' => 'Acadia','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>495, 'make_id' =>25, 'code' =>'CABALLERO','name' => 'Caballero','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>496, 'make_id' =>25, 'code' =>'CANYON', 'name' =>'Canyon','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>497, 'make_id' =>25, 'code' =>'ENVOY', 'name' =>'Envoy','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>498, 'make_id' =>25, 'code' =>'ENVOYXL', 'name' =>'Envoy XL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>499, 'make_id' =>25, 'code' =>'ENVOYXUV', 'name' =>'Envoy XUV','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>500, 'make_id' =>25, 'code' =>'JIM', 'name' =>'Jimmy','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>501, 'make_id' =>25, 'code' =>'RALLYWAG','name' => 'Rally Wagon','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>502, 'make_id' =>25, 'code' =>'GMCS15', 'name' =>'S15 Jimmy','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>503, 'make_id' =>25, 'code' =>'S15', 'name' =>'S15 Pickup','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>504, 'make_id' =>25, 'code' =>'SAFARIGMC','name' => 'Safari','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>505, 'make_id' =>25, 'code' =>'GMCSAVANA','name' => 'Savana','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>506, 'make_id' =>25, 'code' =>'15SIPU4WD', 'name' =>'Sierra C/K1500','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>507, 'make_id' =>25, 'code' =>'GMCC25PU', 'name' =>'Sierra C/K2500','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>508, 'make_id' =>25, 'code' =>'GMC3500PU', 'name' =>'Sierra C/K3500','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>509, 'make_id' =>25, 'code' =>'SONOMA', 'name' =>'Sonoma','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>510, 'make_id' =>25, 'code' =>'SUB', 'name' =>'Suburban','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>511, 'make_id' =>25, 'code' =>'GMCSYCLON','name' => 'Syclone','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>512, 'make_id' =>25, 'code' =>'TERRAIN', 'name' =>'Terrain','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>513, 'make_id' =>25, 'code' =>'TOPC4500', 'name' =>'TopKick C4500','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>514, 'make_id' =>25, 'code' =>'TYPH', 'name' =>'Typhoon','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>515, 'make_id' =>25, 'code' =>'GMCVANDUR','name' => 'Vandura','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>516, 'make_id' =>25, 'code' =>'YUKON', 'name' =>'Yukon','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>517, 'make_id' =>25, 'code' =>'YUKONXL', 'name' =>'Yukon XL','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>518, 'make_id' =>25, 'code' =>'GMCOTH','name' => 'Other GMC Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>519, 'make_id' =>26, 'code' =>'ACCORD', 'name' =>'Accord','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>520, 'make_id' =>26, 'code' =>'CIVIC', 'name' =>'Civic','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>521, 'make_id' =>26, 'code' =>'CRV', 'name' =>'CR-V','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>522, 'make_id' =>26, 'code' =>'CRZ', 'name' =>'CR-Z','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>523, 'make_id' =>26, 'code' =>'CRX','name' => 'CRX','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>524, 'make_id' =>26, 'code' =>'CROSSTOUR_MODELS', 'name' =>'Crosstour and Accord Crosstour Models (2)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>525, 'make_id' =>26, 'code' =>'CROSSTOUR','name' => ' - Accord Crosstour','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>526, 'make_id' =>26, 'code' =>'HONCROSS', 'name' =>' - Crosstour','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>527, 'make_id' =>26, 'code' =>'HONDELSOL','name' => 'Del Sol','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>528, 'make_id' =>26, 'code' =>'ELEMENT','name' => 'Element','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>529, 'make_id' =>26, 'code' =>'FIT','name' => 'Fit','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>530, 'make_id' =>26, 'code' =>'INSIGHT', 'name' =>'Insight','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>531, 'make_id' =>26, 'code' =>'ODYSSEY','name' => 'Odyssey','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>532, 'make_id' =>26, 'code' =>'PASSPO', 'name' =>'Passport','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>533, 'make_id' =>26, 'code' =>'PILOT','name' => 'Pilot','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>534, 'make_id' =>26, 'code' =>'PRE','name' => 'Prelude','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>535, 'make_id' =>26, 'code' =>'RIDGELINE','name' => 'Ridgeline','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>536, 'make_id' =>26, 'code' =>'S2000', 'name' =>'S2000','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>537, 'make_id' =>26, 'code' =>'HONOTH','name' => 'Other Honda Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>538, 'make_id' =>27, 'code' =>'HUMMER', 'name' =>'H1','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>539, 'make_id' =>27, 'code' =>'H2','name' => 'H2','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>540, 'make_id' =>27, 'code' =>'H3','name' => 'H3','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>541, 'make_id' =>27, 'code' =>'H3T','name' => 'H3T','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>542, 'make_id' =>27, 'code' =>'AMGOTH', 'name' =>'Other Hummer Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>543, 'make_id' =>28, 'code' =>'ACCENT','name' => 'Accent','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>544, 'make_id' =>28, 'code' =>'AZERA', 'name' =>'Azera','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>545, 'make_id' =>28, 'code' =>'ELANTR', 'name' =>'Elantra','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>546, 'make_id' =>28, 'code' =>'HYUELANCPE','name' => 'Elantra Coupe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>547, 'make_id' =>28, 'code' =>'ELANTOUR', 'name' =>'Elantra Touring','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>548, 'make_id' =>28, 'code' =>'ENTOURAGE', 'name' =>'Entourage','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>549, 'make_id' =>28, 'code' =>'EQUUS','name' => 'Equus','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>550, 'make_id' =>28, 'code' =>'HYUEXCEL', 'name' =>'Excel','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>551, 'make_id' =>28, 'code' =>'GENESIS', 'name' =>'Genesis','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>552, 'make_id' =>28, 'code' =>'GENESISCPE','name' => 'Genesis Coupe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>553, 'make_id' =>28, 'code' =>'SANTAFE', 'name' =>'Santa Fe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>554, 'make_id' =>28, 'code' =>'SCOUPE','name' => 'Scoupe','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>555, 'make_id' =>28, 'code' =>'SONATA', 'name' =>'Sonata','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>556, 'make_id' =>28, 'code' =>'TIBURO','name' => 'Tiburon','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>557, 'make_id' =>28, 'code' =>'TUCSON','name' => 'Tucson','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>558, 'make_id' =>28, 'code' =>'VELOSTER','name' => 'Veloster','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>559, 'make_id' =>28, 'code' =>'VERACRUZ','name' => 'Veracruz','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>560, 'make_id' =>28, 'code' =>'XG300', 'name' =>'XG300','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>561, 'make_id' =>28, 'code' =>'XG350','name' => 'XG350','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>562, 'make_id' =>28, 'code' =>'HYUOTH','name' => 'Other Hyundai Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>563, 'make_id' =>29, 'code' =>'EX_MODELS', 'name' =>'EX Models (2)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>564, 'make_id' =>29, 'code' =>'EX35', 'name' =>' - EX35','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>565, 'make_id' =>29, 'code' =>'EX37','name' => ' - EX37','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>566, 'make_id' =>29, 'code' =>'FX_MODELS', 'name' =>'FX Models (4)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>567, 'make_id' =>29, 'code' =>'FX35', 'name' =>' - FX35','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>568, 'make_id' =>29, 'code' =>'FX37', 'name' =>' - FX37','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>569, 'make_id' =>29, 'code' =>'FX45', 'name' =>' - FX45','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>570, 'make_id' =>29, 'code' =>'FX50', 'name' =>' - FX50','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>571, 'make_id' =>29, 'code' =>'G_MODELS','name' => 'G Models (4)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>572, 'make_id' =>29, 'code' =>'G20', 'name' =>' - G20','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>573, 'make_id' =>29, 'code' =>'G25','name' => ' - G25','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>574, 'make_id' =>29, 'code' =>'G35', 'name' =>' - G35','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>575, 'make_id' =>29, 'code' =>'G37', 'name' =>' - G37','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>576, 'make_id' =>29, 'code' =>'I_MODELS','name' => 'I Models (2)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>577, 'make_id' =>29, 'code' =>'I30', 'name' =>' - I30','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>578, 'make_id' =>29, 'code' =>'I35', 'name' =>' - I35','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>579, 'make_id' =>29, 'code' =>'J_MODELS', 'name' =>'J Models (1)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>580, 'make_id' =>29, 'code' =>'J30','name' => ' - J30','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>581, 'make_id' =>29, 'code' =>'JX_MODELS','name' => 'JX Models (1)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>582, 'make_id' =>29, 'code' =>'JX35', 'name' =>' - JX35','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>583, 'make_id' =>29, 'code' =>'M_MODELS', 'name' =>'M Models (6)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>584, 'make_id' =>29, 'code' =>'M30','name' => ' - M30','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>585, 'make_id' =>29, 'code' =>'M35','name' => ' - M35','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>586, 'make_id' =>29, 'code' =>'M35HYBRID', 'name' =>' - M35h','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>587, 'make_id' =>29, 'code' =>'M37','name' => ' - M37','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>588, 'make_id' =>29, 'code' =>'M45', 'name' =>' - M45','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>589, 'make_id' =>29, 'code' =>'M56','name' => ' - M56','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>590, 'make_id' =>29, 'code' =>'Q_MODELS','name' => 'Q Models (1)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>591, 'make_id' =>29, 'code' =>'Q45', 'name' =>' - Q45','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>592, 'make_id' =>29, 'code' =>'QX_MODELS','name' => 'QX Models (2)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>593, 'make_id' =>29, 'code' =>'QX4','name' => ' - QX4','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>594, 'make_id' =>29, 'code' =>'QX56','name' => ' - QX56','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>595, 'make_id' =>29, 'code' =>'INFOTH','name' => 'Other Infiniti Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>596, 'make_id' =>30, 'code' =>'AMIGO', 'name' =>'Amigo','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>597, 'make_id' =>30, 'code' =>'ASCENDER','name' => 'Ascender','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>598, 'make_id' =>30, 'code' =>'AXIOM','name' => 'Axiom','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>599, 'make_id' =>30, 'code' =>'HOMBRE','name' => 'Hombre','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>600, 'make_id' =>30, 'code' =>'I280', 'name' =>'i-280','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>601, 'make_id' =>30, 'code' =>'I290', 'name' =>'i-290','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>602, 'make_id' =>30, 'code' =>'I350', 'name' =>'i-350','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>603, 'make_id' =>30, 'code' =>'I370', 'name' =>'i-370','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>604, 'make_id' =>30, 'code' =>'ISUMARK', 'name' =>'I-Mark','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>605, 'make_id' =>30, 'code' =>'ISUIMP','name' => 'Impulse','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>606, 'make_id' =>30, 'code' =>'OASIS', 'name' =>'Oasis','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>607, 'make_id' =>30, 'code' =>'ISUPU', 'name' =>'Pickup','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>608, 'make_id' =>30, 'code' =>'RODEO','name' => 'Rodeo','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>609, 'make_id' =>30, 'code' =>'STYLUS','name' => 'Stylus','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>610, 'make_id' =>30, 'code' =>'TROOP','name' => 'Trooper','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>611, 'make_id' =>30, 'code' =>'TRP2','name' => 'Trooper II','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>612, 'make_id' =>30, 'code' =>'VEHICROSS','name' => 'VehiCROSS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>613, 'make_id' =>30, 'code' =>'ISUOTH', 'name' =>'Other Isuzu Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>614, 'make_id' =>31, 'code' =>'STYPE', 'name' =>'S-Type','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>615, 'make_id' =>31, 'code' =>'XTYPE','name' => 'X-Type','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>616, 'make_id' =>31, 'code' =>'XF', 'name' =>'XF','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>617, 'make_id' =>31, 'code' =>'XJ_SERIES', 'name' =>'XJ Series (10)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>618, 'make_id' =>31, 'code' =>'JAGXJ12','name' => ' - XJ12','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>619, 'make_id' =>31, 'code' =>'JAGXJ6', 'name' =>' - XJ6','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>620, 'make_id' =>31, 'code' =>'JAGXJR','name' => ' - XJR','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>621, 'make_id' =>31, 'code' =>'JAGXJRS', 'name' =>' - XJR-S','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>622, 'make_id' =>31, 'code' =>'JAGXJS', 'name' =>' - XJS','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>623, 'make_id' =>31, 'code' =>'VANDEN', 'name' =>' - XJ Vanden Plas','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>624, 'make_id' =>31, 'code' =>'XJ', 'name' =>' - XJ','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>625, 'make_id' =>31, 'code' =>'XJ8','name' => ' - XJ8','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>626, 'make_id' =>31, 'code' =>'XJ8L','name' => ' - XJ8 L','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>627, 'make_id' =>31, 'code' =>'XJSPORT', 'name' =>' - XJ Sport','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>628, 'make_id' =>31, 'code' =>'XK_SERIES', 'name' =>'XK Series (3)','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>629, 'make_id' =>31, 'code' =>'JAGXK8', 'name' =>' - XK8','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>630, 'make_id' =>31, 'code' =>'XK', 'name' =>' - XK','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>631, 'make_id' =>31, 'code' =>'XKR','name' => ' - XKR','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>632, 'make_id' =>31, 'code' =>'JAGOTH', 'name' =>'Other Jaguar Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>633, 'make_id' =>32, 'code' =>'CHER','name' =>'Cherokee','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>634, 'make_id' =>32, 'code' =>'JEEPCJ','name' => 'CJ','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>635, 'make_id' =>32, 'code' =>'COMANC','name' => 'Comanche','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>636, 'make_id' =>32, 'code' =>'COMMANDER','name' => 'Commander','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>637, 'make_id' =>32, 'code' =>'COMPASS', 'name' =>'Compass','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>638, 'make_id' =>32, 'code' =>'JEEPGRAND', 'name' =>'Grand Cherokee','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>639, 'make_id' =>32, 'code' =>'GRWAG', 'name' =>'Grand Wagoneer','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>640, 'make_id' =>32, 'code' =>'LIBERTY', 'name' =>'Liberty','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>641, 'make_id' =>32, 'code' =>'PATRIOT', 'name' =>'Patriot','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>642, 'make_id' =>32, 'code' =>'JEEPPU', 'name' =>'Pickup','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>643, 'make_id' =>32, 'code' =>'SCRAMBLE','name' => 'Scrambler','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>644, 'make_id' =>32, 'code' =>'WAGONE', 'name' =>'Wagoneer','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>645, 'make_id' =>32, 'code' =>'WRANGLER','name' => 'Wrangler','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>646, 'make_id' =>32, 'code' =>'JEOTH','name' => 'Other Jeep Models','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>647, 'make_id' =>33, 'code' =>'AMANTI', 'name' =>'Amanti','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>648, 'make_id' =>33, 'code' =>'BORREGO','name' => 'Borrego','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>649, 'make_id' =>33, 'code' =>'FORTE','name' => 'Forte','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>650, 'make_id' =>33, 'code' =>'FORTEKOUP','name' => 'Forte Koup','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>651, 'make_id' =>33, 'code' =>'OPTIMA','name' => 'Optima','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>652, 'make_id' =>33, 'code' =>'RIO', 'name' =>'Rio','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>653, 'make_id' =>33, 'code' =>'RIO5','name' => 'Rio5','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>654, 'make_id' =>33, 'code' =>'RONDO','name' => 'Rondo','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>655, 'make_id' =>33, 'code' =>'SEDONA','name' => 'Sedona','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>656, 'make_id' =>33, 'code' =>'SEPHIA', 'name' =>'Sephia','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
      array('id' =>657, 'make_id' =>33, 'code' =>'SORENTO', 'name' =>'Sorento','year' => rand(1970, date('Y')), 'cost'=> $this->frand()),
    );
    DB::table('vehicle_models')->insert($models1);

  }

  function frand($min=1000, $max=10000, $decimals = 2) {
    $scale = pow(10, $decimals);
    return mt_rand($min * $scale, $max * $scale) / $scale;
  }

}

